name: CloudRunify Deployment

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download CloudRunify Binary
        run: |
          curl -L -o cloudrunify "https://github.com/gurneesh9/cloudrunify/releases/download/v0.0.1/cloudrunify-v0.0.1"
          chmod +x cloudrunify
          ls -la cloudrunify
          file cloudrunify
          ./cloudrunify deploy -k json

      - name: Deploy to Cloud Run
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcloud.json
        run: |
          ./cloudrunify deploy -k json


