name: CloudRunify Deployment

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Google Cloud Credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > $HOME/gcloud.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud.json
          gcloud config set project <YOUR_PROJECT_ID>

      - name: Download CloudRunify Binary
        run: |
          curl -L -o cloudrunify "https://github.com/gurneesh9/cloudrunify/releases/download/v0.0.1/cloudrunify-linux-x64-v0.0.1"
          chmod +x cloudrunify
          ls -la cloudrunify

      - name: Deploy to Cloud Run
        run: |
          ./cloudrunify deploy
